# Generated by Django 3.2.6 on 2021-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname1', models.CharField(max_length=30)),
                ('surname2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('tel_no', models.IntegerField(max_length=10)),
                ('message', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['created'],
            },
        ),
    ]
