# Generated by Django 3.2.6 on 2021-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tel_no',
            field=models.IntegerField(),
        ),
    ]
