# Generated by Django 3.2.6 on 2021-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_alter_person_tel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
